# Generated by Django 3.1 on 2020-08-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membershiprequest",
            old_name="bink_message_uid",
            new_name="message_uid",
        ),
        migrations.RenameField(
            model_name="membershiprequest",
            old_name="bink_record_uid",
            new_name="record_uid",
        ),
    ]
