# Generated by Django 3.1 on 2020-09-02 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0002_auto_20200827_1122"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membershiprequest",
            old_name="request_timestamp",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="membershiprequest",
            name="response_body",
        ),
        migrations.RemoveField(
            model_name="membershiprequest",
            name="response_timestamp",
        ),
        migrations.RemoveField(
            model_name="membershiprequest",
            name="status_code",
        ),
        migrations.AlterField(
            model_name="membershiprequest",
            name="message_uid",
            field=models.UUIDField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name="MembershipResponse",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("response_body", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(blank=True)),
                ("status_code", models.IntegerField(blank=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="membership.membershiprequest",
                    ),
                ),
            ],
        ),
    ]
