# Generated by Django 3.1 on 2020-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_auto_20200902_1413"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiprequest",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
