# Generated by Django 4.2.6 on 2024-01-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20210201_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarclaysIdentifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('date_joined', models.DateField()),
                ('bundle_id', models.CharField(blank=True, max_length=250)),
                ('created_link', models.CharField(blank=True, max_length=250)),
                ('scheme_account_id', models.CharField(max_length=250)),
                ('created_scheme_account', models.CharField(max_length=250)),
                ('join_date', models.DateField(blank=True)),
                ('link_date', models.DateField(blank=True)),
                ('card_number', models.CharField(blank=True, max_length=250)),
                ('barcode', models.CharField(blank=True, max_length=250)),
                ('alt_main_answer', models.CharField(blank=True, max_length=250)),
                ('merchant_identifier', models.CharField(blank=True, max_length=250)),
                ('originating_journey', models.CharField(max_length=250)),
                ('scheme_id', models.CharField(max_length=250)),
            ],
        ),
    ]
