# Generated by Django 4.2.6 on 2024-01-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0005_auto_20210201_0912"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChannelIdentifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("date_joined", models.DateTimeField(help_text="User created date")),
                ("bundle_id", models.TextField(help_text="Channel identifier")),
                (
                    "created_link",
                    models.DateTimeField(
                        help_text="Creation date of user to scheme account association",
                        null=True,
                    ),
                ),
                ("scheme_account_id", models.IntegerField()),
                (
                    "created_scheme_account",
                    models.DateTimeField(help_text="Scheme account created date"),
                ),
                (
                    "join_date",
                    models.DateTimeField(help_text="Scheme account join date (if applicable)", null=True),
                ),
                (
                    "link_date",
                    models.DateTimeField(help_text="Scheme account link date (if applicable)", null=True),
                ),
                ("card_number", models.TextField(blank=True, null=True)),
                ("barcode", models.TextField(blank=True, null=True)),
                ("alt_main_answer", models.TextField(blank=True, null=True)),
                ("merchant_identifier", models.TextField(blank=True, null=True)),
                (
                    "originating_journey",
                    models.IntegerField(
                        help_text="Journey type ID (Join = 0, Link = 1, Add = 2, Update = 3, Register = 4, Unknown = 5)"
                    ),
                ),
                ("scheme_id", models.IntegerField()),
            ],
        ),
    ]
