# Generated by Django 3.2.8 on 2022-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0005_auto_20210201_0912"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiprequest",
            name="request_url",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
