# Generated by Django 4.2.6 on 2024-01-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0006_userchannelidentifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userchannelidentifier",
            name="created_scheme_account",
            field=models.DateTimeField(help_text="Scheme account created date", null=True),
        ),
        migrations.AlterField(
            model_name="userchannelidentifier",
            name="originating_journey",
            field=models.IntegerField(
                help_text="Journey type ID (Join = 0, Link = 1, Add = 2, Update = 3, Register = 4, Unknown = 5)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userchannelidentifier",
            name="scheme_account_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="userchannelidentifier",
            name="scheme_id",
            field=models.IntegerField(null=True),
        ),
    ]
