# Generated by Django 3.1 on 2020-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=16)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('request_datetime', models.DateTimeField(blank=True, db_index=True)),
                ('membership_plan', models.CharField(blank=True, db_index=True, max_length=64)),
                ('channel', models.CharField(blank=True, db_index=True, max_length=32)),
                ('http_response_code', models.IntegerField(blank=True)),
                ('response_body', models.JSONField(blank=True)),
                ('payload', models.JSONField(blank=True)),
                ('response_datetime', models.DateTimeField(blank=True, db_index=True)),
            ],
        ),
    ]
