# Generated by Django 3.1 on 2020-08-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
