# Generated by Django 3.1 on 2020-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionRequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("customer_number", models.CharField(blank=True, db_index=True, max_length=250)),
                ("transaction_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("request_timestamp", models.DateTimeField(blank=True, db_index=True)),
                ("membership_plan", models.CharField(blank=True, db_index=True, max_length=64)),
                ("message_uid", models.UUIDField(blank=True, db_index=True)),
                ("record_uid", models.CharField(blank=True, max_length=100, null=True)),
                ("request", models.JSONField(blank=True)),
                ("status_code", models.IntegerField(blank=True)),
                ("response", models.JSONField(blank=True)),
                ("response_timestamp", models.DateTimeField(blank=True, db_index=True)),
            ],
        ),
    ]
