# Generated by Django 3.1.1 on 2021-01-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200908_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ExportTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scheme_provider', models.CharField(db_index=True, max_length=100)),
                ('merchant_identifier', models.CharField(blank=True, db_index=True, max_length=250)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_date', models.DateTimeField(blank=True, db_index=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.auditdata')),
            ],
        ),
    ]
