# Generated by Django 3.1.4 on 2021-01-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200908_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ExportTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=30)),
                ('spend_amount', models.IntegerField(blank=True, help_text='Spend amount (pennies)')),
                ('transaction_date', models.DateTimeField(blank=True, db_index=True)),
                ('loyalty_identifier', models.CharField(blank=True, db_index=True, max_length=250)),
                ('record_uid', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider_slug', models.CharField(db_index=True, max_length=100)),
                ('audit_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.auditdata')),
            ],
        ),
    ]
