# Generated by Django 3.1.4 on 2021-01-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auditdata_exporttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttransaction',
            name='user_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
