# Generated by Django 3.1.4 on 2021-01-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_exporttransaction_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exporttransaction',
            old_name='merchant_identifier',
            new_name='membership_identifier',
        ),
        migrations.RenameField(
            model_name='exporttransaction',
            old_name='scheme_provider',
            new_name='membership_plan',
        ),
        migrations.AddField(
            model_name='exporttransaction',
            name='record_uid',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
