# Generated by Django 3.1.4 on 2021-01-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210120_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdata',
            old_name='data',
            new_name='audit_data',
        ),
        migrations.RenameField(
            model_name='exporttransaction',
            old_name='data',
            new_name='audit_data',
        ),
        migrations.RenameField(
            model_name='exporttransaction',
            old_name='membership_identifier',
            new_name='loyalty_identifier',
        ),
        migrations.RenameField(
            model_name='exporttransaction',
            old_name='membership_plan',
            new_name='provider_slug',
        ),
        migrations.AddField(
            model_name='exporttransaction',
            name='spend_amount',
            field=models.IntegerField(blank=True, default=1, help_text='Spend amount (pennies)'),
            preserve_default=False,
        ),
    ]
