# Generated by Django 2.1.4 on 2019-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_added_to_database", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("email", models.EmailField(max_length=100)),
                ("opt_out_timestamp", models.DateTimeField()),
                ("delete", models.BooleanField(default=False)),
            ],
        ),
    ]
