# Generated by Django 2.1.4 on 2019-01-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquity_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='opt_out',
            new_name='opt_out_timestamp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='local_timestamp',
            new_name='time_added_to_database',
        ),
    ]
